---
proxmox_zabbix_server: "{{ homelab_hosts.monitor01.ip }}"

proxmox_config_backup_hour: "17"
proxmox_config_backup_minute: "00"

proxmox_config_backup_mount: "/mnt/pve/backup-desktop"
proxmox_config_backup_subdir: "host-config"
proxmox_config_backup_keep: 7
