all:
  children:

    managed_linux:
      hosts:
        app01:
          ansible_host: 192.168.1.14

        pihole:
          ansible_host: 192.168.1.10

        runner01:
          ansible_host: 192.168.1.15

        monitor01:
          ansible_host: 192.168.1.12

        myspeed:
          ansible_host: 192.168.1.13

    ansible_control:
      hosts:
        runner01:

    proxmox:
      hosts:
        pve01:
          ansible_host: 192.168.1.101
