---
homelab_network:
  network: "192.168.1.0/24"
  gateway: "192.168.1.254"
  dns: "192.168.1.10"
  domain: "gonella.home"
  dhcp_start: "192.168.1.20"

homelab_ip_plan:
  pihole:
    current_ip: "192.168.1.10"
    new_ip: "192.168.1.10"

  pve01:
    current_ip: "192.168.1.101"
    new_ip: "192.168.1.11"

  monitor01:
    current_ip: "192.168.1.150"
    new_ip: "192.168.1.12"

  myspeed:
    current_ip: "192.168.1.28"
    new_ip: "192.168.1.13"

  app01:
    current_ip: "192.168.1.110"
    new_ip: "192.168.1.14"

  runner01:
    current_ip: "192.168.1.111"
    new_ip: "192.168.1.15"

  labs:
    current_ip: "192.168.1.88"
    new_ip: "192.168.1.16"

homelab_dns_records:
  - ip: "{{ homelab_ip_plan.pihole.new_ip }}"
    hostname: "pihole.gonella.home"

  - ip: "{{ homelab_ip_plan.pve01.new_ip }}"
    hostname: "pve01.gonella.home"

  - ip: "{{ homelab_ip_plan.monitor01.new_ip }}"
    hostname: "monitor01.gonella.home"

  - ip: "{{ homelab_ip_plan.monitor01.new_ip }}"
    hostname: "zabbix.gonella.home"

  - ip: "{{ homelab_ip_plan.myspeed.new_ip }}"
    hostname: "myspeed.gonella.home"

  - ip: "{{ homelab_ip_plan.app01.new_ip }}"
    hostname: "app01.gonella.home"

  - ip: "{{ homelab_ip_plan.runner01.new_ip }}"
    hostname: "runner01.gonella.home"

  - ip: "192.168.1.26"
    hostname: "iphonegonella.gonella.home"

  - ip: "192.168.1.254"
    hostname: "fiberhome.gonella.home"

  - ip: "192.168.3.1"
    hostname: "huawei.gonella.home"
