---
#SPDX-License-Identifier: MIT-0
# tasks file for roles/zabbix_agent2
- name: Garantir Zabbix Agent 2 instalado
  ansible.builtin.apt:
    name: zabbix-agent2
    state: present
    update_cache: true

- name: Configurar servidor Zabbix
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: '^Server='
    line: "Server={{ zabbix_server }}"
  notify: Restart Zabbix Agent 2

- name: Configurar active checks
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: '^ServerActive='
    line: "ServerActive={{ zabbix_server }}"
  notify: Restart Zabbix Agent 2

- name: Configurar hostname do Agent
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: '^Hostname='
    line: "Hostname={{ inventory_hostname }}"
  notify: Restart Zabbix Agent 2

- name: Garantir Zabbix Agent 2 ativo
  ansible.builtin.service:
    name: zabbix-agent2
    state: started
    enabled: true
