---
- name: Garantir Zabbix Agent 2 instalado
  ansible.builtin.apt:
    name: zabbix-agent2
    state: present
    update_cache: true

- name: Verificar arquivo de configuracao do Zabbix Agent 2
  ansible.builtin.stat:
    path: /etc/zabbix/zabbix_agent2.conf
  register: zabbix_agent_config

- name: Configurar servidor Zabbix
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: '^Server='
    line: "Server={{ zabbix_server }}"
  notify: Restart Zabbix Agent 2
  when: zabbix_agent_config.stat.exists

- name: Configurar active checks
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: '^ServerActive='
    line: "ServerActive={{ zabbix_server_active }}"
  notify: Restart Zabbix Agent 2
  when: zabbix_agent_config.stat.exists

- name: Configurar hostname do Agent
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: '^Hostname='
    line: "Hostname={{ zabbix_agent_hostname }}"
  notify: Restart Zabbix Agent 2
  when: zabbix_agent_config.stat.exists

- name: Garantir Zabbix Agent 2 ativo
  ansible.builtin.service:
    name: zabbix-agent2
    state: started
    enabled: true
  when: zabbix_agent_config.stat.exists
