---
- name: Instalar pacotes do Ansible Control Node
  ansible.builtin.apt:
    name:
      - ansible
      - git
      - openssh-client
      - rsync
      - curl
      - wget
      - jq
      - python3
      - python3-pip
    state: present
    update_cache: true

- name: Garantir diretorio SSH do usuario gonella
  ansible.builtin.file:
    path: /home/gonella/.ssh
    state: directory
    owner: gonella
    group: gonella
    mode: '0700'

- name: Garantir diretorio do projeto Ansible
  ansible.builtin.file:
    path: /home/gonella/ansible
    state: directory
    owner: gonella
    group: gonella
    mode: '0755'
