---
- name: Instalar pacotes do Ansible Control Node
  ansible.builtin.apt:
    name:
      - ansible
      - git
      - openssh-client
      - rsync
      - curl
      - wget
      - jq
      - python3
      - python3-pip
    state: present
    update_cache: true

- name: Garantir diretorio SSH do usuario do control node
  ansible.builtin.file:
    path: "{{ ansible_control_home }}/.ssh"
    state: directory
    owner: "{{ ansible_control_user }}"
    group: "{{ ansible_control_user }}"
    mode: '0700'

- name: Garantir diretorio do projeto Ansible
  ansible.builtin.file:
    path: "{{ ansible_control_project_dir }}"
    state: directory
    owner: "{{ ansible_control_user }}"
    group: "{{ ansible_control_user }}"
    mode: '0755'
