---
- name: Padrao Linux - Gonella HomeLab
  hosts: managed_linux
  become: true

  roles:
    - baseline_linux
    - zabbix_agent2

- name: Ansible Control Node - Gonella HomeLab
  hosts: ansible_control
  become: true

  roles:
    - ansible_control_node

- name: Proxmox Host - Gonella HomeLab
  hosts: proxmox
  become: true

  roles:
    - proxmox_host

- name: Pi-hole DNS - Gonella HomeLab
  hosts: pihole
  become: true

  roles:
    - pihole_dns
